=== Untid/KarboClase/EjercicioJAXB/libreria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="autor" type="xs:string"/>
                            <xs:element name="editorial" type="xs:string"/>
                            <xs:element name="paginas" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="isbn" type="xs:string" use="required"/>
                        <xs:attribute name="ejemplares" type="xs:integer"/>
                        <xs:attribute name="anioEdicion" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Untid/KarboClase/EjercicioJAXB/libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="libreria.xsd">
    <libro isbn="978-84-376-0494-7" ejemplares="5" anioEdicion="2020">
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <editorial>Debolsillo</editorial>
        <paginas>471</paginas>
    </libro>
    <libro isbn="978-84-9759-327-8" ejemplares="3" anioEdicion="2018">
        <titulo>El Quijote</titulo>
        <autor>Miguel de Cervantes</autor>
        <editorial>Santillana</editorial>
        <paginas>863</paginas>
    </libro>
    <libro isbn="978-84-206-7273-9" ejemplares="7" anioEdicion="2019">
        <titulo>La sombra del viento</titulo>
        <autor>Carlos Ruiz Zafón</autor>
        <editorial>Booket</editorial>
        <paginas>672</paginas>
    </libro>
</libreria>
